name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: pip install meson ninja

      - name: Install OpenGL
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev
          elif [ "${{ runner.os }}" = "Windows" ]; then
            choco install opengl
          elif [ "${{ runner.os }}" = "macOS" ]; then
            echo "OpenGL should be pre-installed on macOS."
          fi

      - name: Update WrapDB
        run: meson wrap update-db

      - name: Configure Meson
        run: meson setup build

      - name: Build Project
        run: ninja -C build
