name: C/C++ CI for Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: pip install meson ninja

      - name: Update WrapDB
        run: meson wrap update-db

      - name: Configure Meson
        run: meson setup build

      - name: Build Project
        run: ninja -C build
