name: C/C++ CI for Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: pip install meson ninja

      - name: Install OpenGL
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev

      - name: Update WrapDB
        run: meson wrap update-db

      - name: Configure Meson
        run: meson setup build

      - name: Build Project
        run: ninja -C build
